### ISSUE TITLE
Where to add an onClick event?

### ISSUE THREAD

**Issue by MastaBaba** [dhotson/springy#11]
I'm not too great with javascript, let alone the canvas element, and have been unable to add links to the nodes. I suspect I can do some magic inside the drawnode function in springyui.js, but I'm at a loss as to what, exactly.
An onClick event attached to ctx doesn't seem to work, but what would?

Also, it appears that I can't access canvas elements using jQuery (searching for any IDs of elements on the page), which I suppose shows my ignorance in relation to the canvas element.

Some help, or a pointer in the right direction would be much appreciated. Thanks in advance. And thanks for a small js library that's easy to implement :)

**Comment by getyouyou** [comment]
Thank you very much! It's helpful
