### ISSUE TITLE
Html renderer

### ISSUE THREAD

**Issue by maitredede** [dhotson/springy#29]
Hi,

I am trying to make a renderer that uses html elements (instead of canvas).

I would like to know if it is possible to add a renderer option to avoid clear/redraw of nodes/links but only move them.
So I can rely on another graph framework for graphics (like http://jsplumbtoolkit.com/)

Thanks

**Comment by AttilaZz** [comment]
Hi MaitreDede I'm using the same library Jsplumb and I want to do the same what you did, I need help because I'm having a problem " cannot set property mass of undefined.. I know that this post is a bit old... please help
