### ISSUE TITLE
Undirected graphs via JSON

### ISSUE THREAD

**Issue by AlpOzturk** [dhotson/springy#75]
When creating a force directed graph via JSON and springyui, what can I do to ensure that the edges are not directional (i.e. are line segments, don't have arrow heads).

**Comment by dhotson** [comment]
Hi,

You can give edges a `directional` property to specify whether you want arrows drawn or not.

If you're using `graph.loadJSON` to load data, it might look something like this:


```
graph.loadJSON({
  nodes: [ "a", "b"],
  edges: [
    ["a", "b", { directional: false }]
  ]
})
```

**Comment by AlpOzturk** [comment]
Thank you!

-Alp
