### ISSUE TITLE
Changing text color and size for nodes using JSON and springyui

### ISSUE THREAD

**Issue by AlpOzturk** [dhotson/springy#76]
When creating a force directed graph via JSON and springyui, what can I do configure the text size and color for the nodes? I have a hang on manipulating edge properties, but nodes seem trickier.

**Comment by dhotson** [comment]
From memory, you should be able to give nodes a `color` property to set the label's color.

e.g.

```
graph.newNode({label: 'Hello', color: '#FF0000' });
```
