### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by MaxFrax** [dhotson/springy#80]
Hi guys,

after some readings I can't figure out how to improve the image quality of my graph. 
I'd like to show the graph in a canvas with height and width 100% but I can't get a nice resolution
<img width="1280" alt="schermata 2015-11-10 alle 23 30 40" src="https://cloud.githubusercontent.com/assets/3145452/11077948/13d19838-8803-11e5-8d70-88d802eefa57.png">

Thank you all in advance

EDIT: I forgot: if i click into the canvas the nodes move too fast and too much, i think it's a linked problem due to wrong sizing of the view

**Comment by dhotson** [comment]
Are you resizing the canvas with CSS?

You'll need to adjust the canvas width and height attributes on the canvas tag to increase the resolution.

**Comment by MaxFrax** [comment]
Thank you!
