### ISSUE TITLE
Canvas ghosting when creating multiple graph 

### ISSUE THREAD

**Issue by iiSeymour** [dhotson/springy#84]
Any ideas what is going on here: http://stackoverflow.com/q/36604386/1066031

Running the snippet in the linked question and hitting the create graph button a few times causes weird behaviour when mousing over the canvas, the canvas will flicker between the latest graph and a previously rendered graph?

**Comment by co60ca** [comment]
We are getting this as well.

**Comment by co60ca** [comment]
If we change the size in our drawing function we get this ghosting here.

This happens if we change the size of the circle being drawn and manually call renderer.graphChanged();

It seems to be the last graph node we entered

![screenshot_2016-04-16_14-36-26](https://cloud.githubusercontent.com/assets/6857411/14582929/af0ee522-03e0-11e6-8c34-0c8c5dd66aad.png)

**Comment by co60ca** [comment]
Found a local fix for anyone who might be looking for this issue when using canvases with their own renderer.

Say your renderer was doing this.
```
    renderer = new Springy.Renderer(
        layout,
        function clear() {
            canvasctx.clearRect(0, 0, canvaswidth, canvasheight);

        }, ...
```

If you change it to
```
    renderer = new Springy.Renderer(
        layout,
        function clear() {
            // Hack to fully clear the canvas
            canvas.width = canvas.width;
        }, ...
```

This apparently clears all canvas state. Works in my example.

src: http://simonsarris.com/blog/346-how-you-clear-your-canvas-matters

**Comment by iiSeymour** [comment]
I tried setting `cavas.width = canvas.width` and it doesn't seem to make a different, this is with Chrome 49 on mac.

**Comment by iiSeymour** [comment]
I came up with a solution *(full code posted on the [stackoverflow](http://stackoverflow.com/q/36604386/1066031) question)*.

```javascript
var renderer;

function drawGraph(data) {

  if (renderer) {
      renderer.graph.edges.slice().map(function(edge) {
          renderer.graph.removeEdge(edge);
      });
      renderer.graph.nodes.slice().map(function(node) {
          renderer.graph.removeNode(node);
      });
      renderer.graph.loadJSON(data);  
  } else {
      var graph = new Springy.Graph();
      graph.loadJSON(data);
      renderer = $('#graph-canvas').springy({
         graph: graph
      });
  }
}
```
