### ISSUE TITLE
Post-draw function to be called at the end of each frame

### ISSUE THREAD

**Issue by iangilman** [dhotson/springy#96]
I have some updating I need to do at the end of each frame, once all of the nodes have been drawn. I propose we add a callback to the renderer, called something like `afterDraw`. I'm happy to write a pull request if you'd like.

Thanks for the lovely library!

**Comment by dhotson** [comment]
Thank you!

Have a look at the Renderer, you can pass a `onRenderStop` callback that gets called when everything has finished:
https://github.com/dhotson/springy/blob/6158298c9ee183bf95dd34fc49dcb9256d0e46e8/springy.js#L649

.. currently there's no `onRender` to do something every single frame. Feel free to have a got at adding it. I'd be happy to merge. :)

**Comment by iangilman** [comment]
Excellent... will do!
